### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by Fonta1n3**
- More node statistics
- Better UX (especially around booting bitcoin core)
- Cancel buttons when closing/quitting the app
- Show last line of bitcoin debug.log
- Segregate menu file items
- See peer details 
- Fixes issues #102, #101, #100, #99, #96, #97, #98, #104, #89, #87, #90, #95, #103, #91, #126, #121, #124, #120
- Fixes a go private bug

### CODE REVIEW

**Comment by shannona** [comment]
Filed #106, #107, #108, #109, #110, and #111 for issues found with #105. #108 is a critical crash bug, #111 is not quite a crash bug but cranks the memory of the computer and never finishes. #109 has left by Server completely nonfunctional even when I Clean Build Folder and Build from scratch.

**Comment by shannona** [comment]
Also filed #112, #113, #114, #115. Cleared more as I went over time, as far as I know by the time I got to #115, I was really removing everything between reinstalls (~/.tor, ~/.torrc, ~/.gordian, Library/Application\ Support/Bitcoin/, Library/Caches/tor), and I now just get a continuous stream of rpcuser/rpcpasswd errors when I reinstall per #115 (so there's presumably something else I'm not deleting)

**Comment by Fonta1n3** [comment]
> Filed #106, #107, #108, #109, #110, and #111 for issues found with #105. #108 is a critical crash bug, #111 is not quite a crash bug but cranks the memory of the computer and never finishes. #109 has left by Server completely nonfunctional even when I Clean Build Folder and Build from scratch.

My latest commits should fix #106, #107, #109, #111.

Not able to replicate #108, #110.

I had not tested the "Kill all" switch and a lot was wrong, you should have a much better time testing now. Also there is no need to manually delete anything as the kill switch does get rid of it all.

**Comment by Fonta1n3** [comment]
> Also filed #112, #113, #114, #115. Cleared more as I went over time, as far as I know by the time I got to #115, I was really removing everything between reinstalls (~/.tor, ~/.torrc, ~/.gordian, Library/Application\ Support/Bitcoin/, Library/Caches/tor), and I now just get a continuous stream of rpcuser/rpcpasswd errors when I reinstall per #115 (so there's presumably something else I'm not deleting)

#114 and #115 fixed. 

#112 should be (please see comment on the issue).

**Review by ChristopherA — APPROVED** [review]
Built successfully Macbook Air (M1 2020) under macOS Big Sur 11.6 using Xcode Version 13.0 (13A233). Tested pruned mainnet node, with Fully Noded, and Gordian Wallet.

Approved merge to master. May need some more tweaks & docs to approve for tag 1.0.0.

**Review by shannona — APPROVED** [review]
Built successfully on Mac Mini (Quad-Core Intel Core i3, 2018) under macOS Big Sur 11.5.2 using Xcode Version 13.0 (13A233). Various tests of pruned mainnet and testnet with Gordian Wallet and Fully Noded.

Approved merge. Please consult remaining issues from #87 up for ones either flagged "do next" or any that look like easy additions to finalize this iteration. Current plan is for a 1.0.0 release tag and DMG creation next week, after these final, minor changes.

**Pull request merged**
