### PR TITLE
v0.1.3 ⚠️ Critical bug fix, improved default bitcoin.conf settings, more wallet interaction

### PR DESCRIPTION
**Pull request by Fonta1n3**
- The default bitcoin.conf is now much smarter, we now use automatic pruning with the amount set to half the available disc space. We set the `dbcache` to half the ram of the device. We add `maxuploadtarget` and `maxconnections` to keep bandwidth usage at a minimum, a `fallbackfee` to avoid errors when using the nodes fee estimator on a pruned node, add `rpcallowip=127.0.0.1` just for good practice.

- ⚠️ Bug fix which could have resulted in a "network request" error upon initial install, this was caused due to checking a potential error message for an empty string when it should have checked for nil.

- General refactoring

- Add ability to set and edit a non boolean value for pruning and by default set it to half available disc space

- Fix a bug where tor proxy bitcoin.conf settings would get duplicated if commented out during install

- Make the standup.command script more modular and hardened so that we always check if things exist before creating or downloading them, previously you could run into some issues if you already had tor and hidden services configured, this should no longer be the case

- If any tor related commands fail during standup then the script will fail instead of complete without installing tor

- Add ability to open `bitcoin.conf` and `torrc` from settings panel

- Create a hidden directory in the home folder `~/.standup` instead of `~/StandUp`

- More verbose standup dialogue especially in the scenario where tor is already installed

- Add network name to window title of Quickconnect QR

- `Standup.command` no longer auto starts tor or bitcoind as that causes too much of a lagging rainbow spinner of death... Therefore a user needs to manually click start after the installation script completes

- Because the home directory has been changed to `.standup` you may be prompted to “standup” even if you have a Standup directory already 

- Add ability to see all wallets per chain and to delete them, to see additional wallet actions just double click the wallet

### CODE REVIEW

**Comment by ChristopherA** [comment]
Non-critical bug for this PR. Wallets button should be dimmed until bitcoin is started as it depends on Bitcoin running first.

**Comment by Fonta1n3** [comment]
> Non-critical bug for this PR. Wallets button should be dimmed until bitcoin is started as it depends on Bitcoin running first.

https://github.com/BlockchainCommons/GordianServer-macOS/pull/52/commits/991ae7f3fc6d49d0eb0cafdf119c75034791025b fixes this

**Review by ChristopherA — APPROVED** [review]
+1 Built on MacOS Catalina 10.15.6, using Xcode Version 11.7. Tested with existing installation of Bitcoin Core data. Mainnet & Testnet sync achieved. Tested adding testnet full node via quickconnect to Gordian Wallet 0.1.81, and adding a wallet, and it worked.

**Review by ChristopherA — APPROVED** [review]
Approved to merge to Master branch.

**Pull request merged**
