### PR TITLE
⚡️ C-Lightning - GordianServer-macOS-v0.1.4

### PR DESCRIPTION
**Pull request by Fonta1n3**
⚡️ This PR adds the ability to install [C-Lightning v0.9.1](https://github.com/ElementsProject/lightning/releases/tag/v0.9.1), along with various other improvements and includes a notarized and pgp signed dmg.

⚠️ This is a minimum viable product, it does not make any effort to verify gpg signatures during install, yet.

All long running tasks are now performed on a background thread which should improve general app performance.

Along with installing c-lightning the user may start, stop and connect remotely to their c-lightning node via a QuickConnect QR code, this functionality can be tested with [Fully Noded](https://apps.apple.com/us/app/fully-noded/id1436425586) or via the terminal and in the near future [GordianWallet](https://github.com/BlockchainCommons/GordianWallet-iOS).

To access `lightning-cli` manually:

```
$ cd ~/.standup/lightning
$ cli/lightning-cli help
```

Users may also easily view their lightning log and config via the settings button.

This has been tested on macOS Catalina and Mojave, on a fresh VMWare and my personal desktop.

⚠️ Please note you will not be able to install c-lightning unless `bitcoind` is installed. You will not be able to start `c-lightning` unless `bitcoind` mainnet is running. The hidden service for connecting to c-lightning remotely is configured in the main `standup` script, therefore in order to test remote connection please delete your `~\.standup` directory and go through the install process from scratch.

The install script installs this [plugin](https://github.com/Start9Labs/c-lightning-http-plugin) for exposing `lightning-cli` to an http server which is exposed to `localhost` and a Tor V3 hidden service which controls port `1312`.

### CODE REVIEW

**Comment by Fonta1n3** [comment]
Just tested on my wife's older macbook, looks like it had an issue with `pip` not being installed and `pyenv 3.7.4` not being installed. Will need to address those two issues. If you run into a similiar issue try installing `pip` and `pyenv 3.7.4` to resolve it.

**Comment by Fonta1n3** [comment]
@ChristopherA this is ready for review.

**Comment by ChristopherA** [comment]
I did successfully build on on macOS Catalina (10.15.6), using Xcode 11.7. 

I did not re-test install full node, but I did try the install c-lightning button. I did not go to the C-Lightning settings (testing that default setup would work).

At end of install (it looked in everything was installed), progress window disappeared with no error.

However, in C-Lightning section the "Install" button is back, no details or active QuickConnect button

At tail of the tail log I have:

```
Sep 23 00:23:33.000 [notice] New control connection opened from 127.0.0.1.
Sep 23 00:23:40.000 [notice] New control connection opened from 127.0.0.1.
Sep 23 00:23:42.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Sep 23 00:24:34.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Sep 23 00:25:17.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Sep 23 00:27:04.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Sep 23 00:28:13.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
```

Two problems: that no error was given after install progress window went away. Then whatever error is causing this problem.

I am emailing full log to @Fonta1n3

**Comment by Fonta1n3** [comment]
@ChristopherA bitcoin mainnet must be running or you will not have the option to start lightning.

**Comment by ChristopherA** [comment]
Oops, did send wrong log. LIghtining Log is empty. Is there an install log?

I do have Bitcoin Core Full running, and it is fully synced.

**Comment by Fonta1n3** [comment]
The issue is it is required (as the PR stands) that you need to install everything from scratch as the lightning hidden service’s are configured at the same time as the Bitcoin Core hidden service’s. I will make it more backward compatible so a fresh install is not required 👍

**Comment by Fonta1n3** [comment]
@ChristopherA the lightning install script has been edited for better backwards compatibility and is now ready for testing and merging.

**Comment by Fonta1n3** [comment]
Until https://github.com/ElementsProject/lightning/issues/4098 is resolved this PR should not be merged. We really ought to be packaging c-lightning into a reproducible signed tar ball for OSX to avoid numerous issues that can arise from building things from source. This PR as it stands works great for me though, on Catalina 10.15.4 Beta.

**Comment by Fonta1n3** [comment]
@ChristopherA This was the comment I received regarding the specific issue you faced for building c-lightning:

"Hi, I'm writing you because I see issue #4098 and I saw some error like that inside a build procedure in my machine when the libwally was updated, sometimes is necessary remove by hand the build directory inside the external directory. In my case is called "x86_64-linux-gnu"

**Comment by Fonta1n3** [comment]
@ChristopherA I have improved the UX around the log file, added a #reckless button for c-lightning installation and the log now lives in ~/.standup/standup.log as well as fixed the authentication blurb from being cut off.

To test there is no need to "stand down" but I do recommend deleting the `~/.standup` directory for testing which will **not** effect your hidden services or node.

**Comment by Fonta1n3** [comment]
https://github.com/BlockchainCommons/GordianServer-macOS/pull/54/commits/3b9fb61e812a872d46658c8bd2219ca4fd1abda7 fixes #57 #58 #59

**Comment by ChristopherA** [comment]
After the C-Lightning installed in #54, I had to do a force-quit, but I did let my VM chug along to complete it's pruned node. It took about two days. However, once it was fully synced, though the C-Lighting pane said "Start", if you clicked it it would percolate for a little bit than nothing. No error message. 

I'll save this VM as well as the ~/Library/Application\ Support/Bitcoin files offline. in order to not have to wait two days try to test #60 to later to see if this problem still happens in that PR as well.

**Pull request closed without merging**
