### PR TITLE
signed CLA

### PR DESCRIPTION
**Pull request by henkvancann**
Hi Chris/Peter,

I created this signed CLA with this terminal-command, pls check whether you can verify

gpg --armor -u 2532B8C230DBD503 --clearsign --output ./Docs/signed-cla/CLA.henkvancann.2532B8C230DBD503.asc CLA.md

Best, Henk

### CODE REVIEW

**Comment by ChristopherA** [comment]
It is a valid signature, but the repo name is incorrect — it should be this repo.

**Comment by henkvancann** [comment]
Copy Paste error. should be solved now. 

My intention is to create a Q-and-A.md in Docs dir as I go through StandUp MacOs myself. Have a clean Mac to try out.

**Review by ChristopherA — APPROVED** [review]
Thank you for joining us as a contributor!

**Comment by ChristopherA** [comment]
Now the problem is that either this commit wasn’t GPG signed `git commit -S -m “commit message”` or that your GPG public key has not been uploaded to your GitHub profile, or an email address that valid for GitHub is not listed in your GPG public key.

**Comment by henkvancann** [comment]
Ha, take 3, forgot the - S option. The rest I've taken care of, at least I think I did.

**Comment by henkvancann** [comment]
I remember that with my old Mac the commits were signed automatically (no need for -S )... Have to figure out how that can be automated

**Comment by henkvancann** [comment]
Yep, bingo: https://stackoverflow.com/questions/10161198/is-there-a-way-to-autosign-commits-in-git-with-a-gpg-key

**Comment by ChristopherA** [comment]
Yes, I see that the new commit is marked with the green "verified". The problem now is that the old unsigned commits are still there. 

There are two options, you can puzzle through how to amend those commits — past people with this problem have found insights in https://superuser.com/questions/397149/can-you-gpg-sign-old-commits

The easiest option though is to close this PR and create another.

**Pull request closed without merging**
